name: Build

on:
    push:
        branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
            
    #   - name: Run Unit Tests
    #     run: |
    #         go test ./internals/handlers

      - name: Build
        run: go build -v ./cmd/api